name: Build container release images
on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  check-latest-stable:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.check.outputs.is_latest_stable }}
    steps:
      # Repository needs to be cloned to list branches
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      push_to_images: |
        ghcr.io/hometown-fork/hometown
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit

  build-image-streaming:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      push_to_images: |
        ghcr.io/hometown-fork/hometown-streaming
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit
